#!/bin/sh

# myscan – a simple document scanner
#
# Copyright © 2011 Johan Kiviniemi <devel@johan.kiviniemi.name>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

set -e

if [ "$#" -ne 1 ]; then
  >&2 printf 'USAGE: %s output.pdf\n' "$0"
  exit 1
fi

programs_exist=true
for f in mktemp scanimage convert unpaper; do
  if ! >/dev/null 2>&1 type "$f"; then
    >&2 printf "Missing program: %s\n" "$f"
    programs_exist=false
  fi
done
"$programs_exist"

mymktemp() {
  mktemp --tmpdir myscan.XXXXXXXXXX
}

res=300

tempfiles=
trap 'rm -f $tempfiles' 0 1 2 13 15

scan="$(mymktemp)"
tempfiles="${tempfiles:+$tempfiles }$scan"
scanimage -p --compression=None --resolution="$res" --mode=Color >"$scan"

contrast="$(mymktemp)"
tempfiles="${tempfiles:+$tempfiles }$contrast"
convert -verbose "pnm:$scan" -level 20%,80% "pnm:$contrast"

unpaper="$(mymktemp)"
tempfiles="${tempfiles:+$tempfiles }$unpaper"
unpaper --dpi "$res" --post-size a4 \
        --no-noisefilter --no-blurfilter --no-grayfilter --no-deskew \
        --overwrite -v "$contrast" "$unpaper"

pdf="$(mymktemp)"
tempfiles="${tempfiles:+$tempfiles }$pdf"
convert -verbose -density "$res" "pnm:$unpaper" "pdf:$pdf"

mv -f "$pdf" "$1"

# vi:set et sw=2 sts=2:
